# Generated by Django 4.2 on 2025-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_producto_impuesto_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
