# Generated by Django 4.2 on 2025-11-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_usuario_codigo_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='impuesto_defecto',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
