# Generated by Django 4.2 on 2025-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_empresa_codigo_validacion_empresa_validado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
