# Generated by Django 4.2 on 2025-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_producto_precio_oferta_producto_tiene_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
