# Generated by Django 4.2 on 2025-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_producto_oferta_fin_producto_oferta_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descuento_fidelizacion',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de descuento', max_digits=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dias_para_fidelizacion',
            field=models.IntegerField(default=30, help_text='Días después de la última cotización para enviar correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fidelizacion_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mensaje_fidelizacion',
            field=models.TextField(blank=True, default='Te extrañamos. Aquí tienes un descuento especial para tu próxima compra.'),
        ),
    ]
