# Generated by Django 4.2 on 2025-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_empresa_descuento_fidelizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto_especifico',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de impuesto específico', max_digits=10),
        ),
    ]
