# Generated by Django 4.2 on 2025-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
