# Generated by Django 4.2 on 2025-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='color_boton_principal',
            field=models.CharField(default='#646cff', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='color_fondo_pagina',
            field=models.CharField(default='#121212', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='color_menu_sidebar',
            field=models.CharField(default='#1e1e1e', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='color_texto_principal',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='color_texto_secundario',
            field=models.CharField(default='#b3b3b3', max_length=20),
        ),
    ]
