# Generated by Django 4.2 on 2025-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_empresa_color_boton_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='color_borde',
            field=models.CharField(default='rgba(255, 255, 255, 0.1)', max_length=50),
        ),
    ]
