# Generated by Django 4.2 on 2025-12-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_empresa_color_borde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('descuento_ofrecido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mensaje_enviado', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
    ]
