# Generated by Django 4.2 on 2025-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_remove_trabajador_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dias_inicio_fidelizacion',
            field=models.IntegerField(default=7, help_text='Inicio: Días después del registro para enviar el primer correo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dias_para_fidelizacion',
            field=models.IntegerField(default=30, help_text='Frecuencia: Días entre cada correo de promoción'),
        ),
    ]
