# Generated by Django 4.2 on 2025-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_empresa_dias_inicio_fidelizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='moneda_codigo',
            field=models.CharField(default='CLP', max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda_decimales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda_simbolo',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
