# Generated by Django 4.2 on 2025-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_empresa_moneda_codigo_empresa_moneda_decimales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento por ítem', max_digits=5),
        ),
    ]
