# Generated by Django 4.2 on 2025-12-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_detallecotizacion_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='impuesto_especifico',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de impuesto específico (Legacy)', max_digits=10),
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('FIJO', 'Monto Fijo ($)')], default='PORCENTAJE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='gestion.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_adicional',
            field=models.ForeignKey(blank=True, help_text='Impuesto específico seleccionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='gestion.impuesto'),
        ),
    ]
