# Generated by Django 4.2 on 2025-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_producto_impuesto_especifico_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='aplicacion',
            field=models.CharField(choices=[('NETO', 'Sobre Neto'), ('TOTAL', 'Sobre Total (Neto + IVA)')], default='NETO', max_length=10),
        ),
    ]
