# Generated by Django 4.2 on 2025-12-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_impuesto_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuestos',
            field=models.ManyToManyField(blank=True, help_text='Impuestos adicionales aplicables', related_name='productos_m2m', to='gestion.impuesto'),
        ),
    ]
