# Generated by Django 4.2 on 2025-12-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_producto_impuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='valor',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='impuesto_especifico',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Monto fijo de impuesto específico (Legacy)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
